// Class automatically generated by Dev-C++ New Class wizard

#include "analizador.h" // class's header file

// class constructor
Analizador::Analizador()
{             
    Fl_Repeat_Button *oSel_mult;
    Fl_Knob *atiempo_div;
      
    strcpy(cvalor,"0.000");
    
    oana_on = new Fl_Light_Button(570,645,30,20,"ON");
    oana_on->labelsize(9);
    
    ogroup_mult = new Fl_Group (5,370,600,300,"");
    ogroup_mult->box(FL_ENGRAVED_FRAME);
    ogroup_mult->deactivate();  
   
    apantalla = new Fl_Scope(8,375,380, 290,"");  // Instancia de scope
    apantalla->TraceColour(FL_WHITE);
    apantalla->tracetype(FL_SCOPE_TRACE_LOOP);
    apantalla->redrawmode(FL_SCOPE_REDRAW_FULL);
    apantalla->linetype(FL_SCOPE_LINE);  
    
    ogroup_ana_botones = new Fl_Group (450,395,85,90,"");    // Agrupa los elementos del osciloscopio
    ogroup_ana_botones->box(FL_ENGRAVED_FRAME); 
    ogroup_ana_botones->deactivate();
    
    atiempo_div = new Fl_Knob(455,400,70,70,"CANAL");
    atiempo_div->color(147);
    atiempo_div->type(8);
    atiempo_div->labelsize(9);
    atiempo_div->scaleticks(8);
    atiempo_div->range(0,100);
    
    ogroup_mult->end();
    oana_on->callback(cb_ana_on, this);
     
    //amult_on->callback(cb_mult_on, this);
}

// class destructor
Analizador::~Analizador()
{

}

void Analizador::cb_ana_on(Fl_Widget* pboton, void *pany)
{
     Analizador* pana=(Analizador*)pany;
     pana->cb_ana_on_in();
}

void Analizador::cb_ana_on_in(){
      if(oana_on->value()== 1){
        activar(1);
        /*Fl::add_timeout(0.5, cb_timer_ch1, this);*/
     }
     if(oana_on->value()== 0){
        /*Fl::remove_timeout(cb_timer_ch2, this);*/
        activar(0);
     }
     //isec_ch++;
}
