// Class automatically generated by Dev-C++ New Class wizard

#ifndef GENERADOR_H
#define GENERADOR_H

#include "instrumento.h"                    //Inheriting class's header file
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <Fl/fl_Light_Button.h>
#include <Fl/fl_Button.h>
#include <FL/Fl_Box.H>
#include <FL/Fl_Repeat_Button.H>
#include "Fl_7Seg.H"                        //Class's header file
#include "fl_Knob.h"
#include <FL/Fl_Counter.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Shared_Image.H>
#include <FL/Fl_PNG_Image.H>
#include <math.h>
#include <windows.H>

using namespace std;
 
//Factor por el que se debe multiplicar el valor del botón de frecuencia para 
//obtener el valor en la escala del chip generador de señales.
#define FACTOR 0.18626451561698509610066226162263                       

/*******************************************************************************
 * Generador: Clase que representa el funcionamiento del instrumento generador 
 *            de señales.
 * El instrumento genera 3 clases de señales: Seno, Cuadrada y Triángulo.
 * De cada una de las señales mensionadas se puede controlar la frecuencia, la           
 * amplitud y el nivel dc (offset).
 * El instrumento cuenta con un display donde se verá la frecuencia configurada.
*******************************************************************************/
class Generador : public Instrumento
{
	public:
		// class constructor
		Generador();
		// class destructor
		~Generador();
	private:
		//valor de la frecuencia configurada en representación hexadecimal.
		char frecHexa [8];
		//valor de la amplitud de la señal configurada en hexadecimal.
		char amplitudHexa [8];
		//valor del nivel de offset configurada en hexadecimal.
		char offsetHexa [8];
        //Grupo de los botones e indicadores del generador de señales
		Fl_Group *ogroupGenerador;
		//Box para colocar la mascara del generador.
	    Fl_Box *boxgroupgen;
	    //Mascara del generador de señales.
	    Fl_PNG_Image *igen;
		//Grupo de los botones para ajustar la frecuencia de la señal generada
		Fl_Group *ogroupFrecuencia;
		//Grupo de los botones e indicadores para seleccionar la señal generada
		Fl_Group *ogroupSenal;
		//Grupo de los botones para seleccionar la amplitud de la señal generada.
		Fl_Group *ogroupAmplitud;
		//Grupo de los botones para seleccionar el nivel de offset de la señal generada.
		Fl_Group *ogroupOffset;
		//Contiene el nombre del instrumento.
	    Fl_Box *oboxNombre;
		//Botón para prender el instrumento generador de señales.
		Fl_Light_Button *ogenOn;
		//Display del generador donde se visualiza el valor de frecuencia configurado.
		Fl_7Seg *odispGen;
		//Botón que habilita la ayuda al usuario sobre el manejo del instrumento.
        Fl_Button *ohelpGen;
        //Botón de seleccion de tipo de señal seno.
        Fl_Button *oseno;
        //Botón de seleccion de tipo de señal cuadrada.
        Fl_Button *ocuadrada;
        //Botón de seleccion de tipo de señal triángulo.
        Fl_Button *otriangulo;
        // Indicador del valor de la frecuencia en la escala de miliHertz.
        Fl_Box *omHz;
        // Indicador del valor de la frecuencia en la escala de Hertz.
        Fl_Box *oHz;
        // Indicador del valor de la frecuencia en la escala de MegaHertz.
        Fl_Box *oMeHz;
        // Botón de ajuste lineal de la frecuencia de la señal.
        Fl_Knob *ofrecGen;
        //Botón de ajuste lineal fino de la frecuencia de la señal .
        Fl_Knob *ofrecGen2;
        //Indicador del Valor de la frecuencia de la señal seleccionada por el ususario.
        Fl_Value_Input *ovalorFrec;
        //Botón de ajuste lineal de la amplitud de la señal seleccionada por el ususario.
        Fl_Knob *oamplitud;
        // Display que muestra el valor de la amplitud de la señal seleccionada por el ususario.
        Fl_Output *odispAmplitud;
        //Botón de ajuste lineal del nivel de offset de la señal seleccionada por el ususario.
        Fl_Knob *ooffset;
        //Display que muestra el valor del nivel de offset de la señal seleccionada por el ususario.
        Fl_Output *odispOffset; 
        //Menú selector de escalas de frecuencia.
        Fl_Choice *oescalaFrecuencia;
        //Callback del botón de encendido/apagado del generador de señales.
		static void cbGeneradorOn(Fl_Widget*, void *);
		inline void cbGeneradorOnIn();
		//Callback del botón de selección de señal seno.
		static void cbSeno(Fl_Widget*, void *);
		inline void cbSenoIn();
		//Callback del botón de selección de señal cuadrada.
		static void cbCuadrada(Fl_Widget*, void *);
		inline void cbCuadradaIn();
		//Callback del botón de selección de señal triángulo.
		static void cbTriangulo(Fl_Widget*, void *);
		inline void cbTrianguloIn();
		//Callback del botón que selecciona la frecuencia de la señal generada.
		static void cbFrecGen(Fl_Widget*, void *);
		inline void cbFrecGenIn();
		//Callback del botón que realiza el ajuste fino de la frecuencia de la señal generada.
		static void cbFrecgen2(Fl_Widget*, void *);
		inline void cbFrecgen2In();
		//Calback para la escala de frecuencias hasta 1 Hertz
		static void cbFrec1(Fl_Widget*, void *);
		inline void cbFrec1In(Fl_Widget*);
		//Calback para la escala de frecuencias hasta 100 Hertz
		static void cbFrec100(Fl_Widget*, void *);
		inline void cbFrec100In(Fl_Widget*);
		// Calback para la escala de frecuencias hasta 500 Hertz
		static void cbFrec500(Fl_Widget*, void *);
		inline void cbFrec500In(Fl_Widget*);
		// Calback para la escala de frecuencias hasta 1 KHz
		static void cbFrec1k(Fl_Widget*, void *);
		inline void cbFrec1kIn(Fl_Widget*);
		//Calback para la escala de frecuencias hasta 100 KHz
		static void cbFrec100k(Fl_Widget*, void *);
		inline void cbFrec100kIn(Fl_Widget*);
		//Calback para la escala de frecuencias hasta 500 KHz
		static void cbFrec500k(Fl_Widget*, void *);
		inline void cbFrec500kIn(Fl_Widget*);
		//Calback para la escala de frecuencias hasta 1 MHz
		static void cbFrec1m(Fl_Widget*, void *);
		inline void cbFrec1mIn(Fl_Widget*);
		//Callback del botón que selecciona la amplitud de la señal generada.
		static void cbAmplitud(Fl_Widget*, void *);
		inline void cbAmplitudIn();
		//Callback del botón que selecciona el nivel de offset de la señal generada.
		static void cbOffset(Fl_Widget*, void *);
		inline void cbOffsetIn();
        
};

#endif // GENERADOR_H
