// Class automatically generated by Dev-C++ New Class wizard

#ifndef MENSAJES_H
#define MENSAJES_H

#ifndef Fl_Widget_H
#include <FL/Fl_Widget.H>
#include <FL/Fl_Ask.H>

#include <stdlib.h>
#include <iostream>
#include <string>
using namespace std;
#endif



/******************************************************************************* 
* Mensajes: Clase para numerar las muestras graficadas en el instrumento Anali-
*           zador Lógico.
* La clase grafica una numeración que indica que numero de muestra está grafica-
* da en la pantalla del instrumento.
* La numeración empieza en cero y termina en el número de muestras configurado 
* en el objeto Analizador Lógico. 
*******************************************************************************/
class Mensajes : public Fl_Widget{
          
          //Posicion del Texto 
          int  _x,_y;
          //Color de texto                          
          Fl_Color _TextColour;               
          //Número graficado
          char text[4];                       
      
protected:
          //Método sobrecargado para graficar
          void draw(int,int,int,int);
          //Método heredado para graficar          
          void draw();
          //Posición de inicio en eje X
          void x(int X){ _x=X;};
          //Posición de inicio en eje Y               
          void y(int Y){ _y=Y;};              

public:
       // Número de muestras que se grafican en la pantalla del analizador
       int inum_muestras;                      
       // Posicion horizontal del Texto 
       int x(){return _x;};                    
       // Posicion vertical del Texto 
       int y(){return _y;};                    
       // Número que se cooca en la primera posición a la izquierda de la pantalla
       int inum_inicial;                       
       // Método para modificar el color del texto
       Fl_Color TextColour(){return _TextColour;};
       void     TextColour(Fl_Color c){_TextColour=c;};
	   //Constructor de clase
	   Mensajes(int,int,int,int,const char * = 0);
       // class destructor
	   ~Mensajes();
};

#endif // MENSAJES_H
